# ---------------------------------------------------------------------------
# 02c. Calculate UIC Registrations lat & long values.py
# Created on: Fri Apr 09 2010 12:44:08 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
UIC_Registration_spatial_temp__1_ = "\\\\Oberon\\GRP104\\UIC_Management_Program\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial_temp"
UIC_Registration_LatLong = "\\\\Oberon\\GRP104\\UIC_Management_Program\\Registrations\\UIC_Registration.mdb\\UIC_Registration_LatLong"
UICs_Registration_temp__2_ = "\\\\Oberon\\GRP104\\UIC_Management_Program\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial_temp"
UIC_Registration_LatLong__1_ = "\\\\Oberon\\GRP104\\UIC_Management_Program\\Registrations\\UIC_Registration.mdb\\UIC_Registration_LatLong"
UIC_Registration_Spatial__1_ = "\\\\Oberon\\GRP104\\UIC_Management_Program\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial"
Delete_succeeded__1_ = "true"
Delete_succeeded__2_ = "true"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_LatLong__1_, "FeatureClass")

# Process: Project (1)...
tempEnvironment0 = gp.outputCoordinateSystem
gp.outputCoordinateSystem = "GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983_HARN',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]"
gp.Project_management(UIC_Registration_Spatial__1_, UIC_Registration_spatial_temp__1_, "GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983_HARN',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")
gp.outputCoordinateSystem = tempEnvironment0

# Process: Add XY Coordinates (2)...
gp.AddXY_management(UIC_Registration_spatial_temp__1_)

# Process: Copy (1)...
gp.Copy_management(UICs_Registration_temp__2_, UIC_Registration_LatLong, "")

# Process: Delete (2)...
gp.Delete_management(UIC_Registration_spatial_temp__1_, "")

