# ---------------------------------------------------------------------------
# 02e. Reproject UICs to UTM1083.py
# Created on: Fri Apr 09 2010 12:46:27 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
WaterUICs__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\WaterUICs"
ParksUICs__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\ParksUICs"
BGSUICs__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BGSUICs"
BESUICs__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BESUICs"
Delete_succeeded__1_ = "true"
BESUICs_UTM1083 = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BESUICs_UTM1083"
BGSUICs_UTM1083 = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BGSUICs_UTM1083"
FireUICs_UTM1083 = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\FireUICs_UTM1083"
ParksUICs_UTM1083 = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\ParksUICs_UTM1083"
WaterUICs_UTM1083 = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\WaterUICs_UTM1083"
WaterUICs_UTM1083__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\WaterUICs_UTM1083"
ParksUICs_UTM1083__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\ParksUICs_UTM1083"
FireUICs_UTM1083__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\FireUICs_UTM1083"
BGSUICs_UTM1083__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BGSUICs_UTM1083"
BESUICs_UTM1083__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\BESUICs_UTM1083"
Delete_succeeded__2_ = "true"
Delete_succeeded__3_ = "true"
Delete_succeeded__4_ = "true"
Delete_succeeded__5_ = "true"
FireUICs__1_ = "\\\\Cassio\\GIS2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\FireUICs"

# Process: Delete (1)...
gp.Delete_management(BESUICs_UTM1083__1_, "FeatureClass")

# Process: Project (1)...
gp.Project_management(BESUICs__1_, BESUICs_UTM1083, "PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")

# Process: Delete (2)...
gp.Delete_management(BGSUICs_UTM1083__1_, "FeatureClass")

# Process: Project (2)...
gp.Project_management(BGSUICs__1_, BGSUICs_UTM1083, "PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")

# Process: Delete (3)...
gp.Delete_management(FireUICs_UTM1083__1_, "FeatureClass")

# Process: Project (3)...
gp.Project_management(FireUICs__1_, FireUICs_UTM1083, "PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")

# Process: Delete (4)...
gp.Delete_management(ParksUICs_UTM1083__1_, "FeatureClass")

# Process: Project (4)...
gp.Project_management(ParksUICs__1_, ParksUICs_UTM1083, "PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")

# Process: Delete (5)...
gp.Delete_management(WaterUICs_UTM1083__1_, "FeatureClass")

# Process: Project (5)...
gp.Project_management(WaterUICs__1_, WaterUICs_UTM1083, "PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "PROJCS['NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',8202099.737532808],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-120.5],PARAMETER['Standard_Parallel_1',44.33333333333334],PARAMETER['Standard_Parallel_2',46.0],PARAMETER['Latitude_Of_Origin',43.66666666666666],UNIT['Foot',0.3048]]")

