# ---------------------------------------------------------------------------
# createPGDB.py
# Created on: Wed Apr 07 2010 06:02:24 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
uic_mdb = "c:\\temp\\uic.mdb"
temp = "c:\\temp"

# Process: Create Personal GDB...
gp.CreatePersonalGDB_management(temp, "uic")

