# ---------------------------------------------------------------------------
# latlong.py
# Created on: Thu Apr 08 2010 08:40:55 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
uic_Layer1 = "uic_Layer1"
LatLong = "C:\\temp\\uic.mdb\\LatLong"
uic = "C:\\temp\\uic.mdb\\uic"
uic_mdb = "C:\\temp\\uic.mdb"

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(uic, uic_Layer1, "", uic_mdb, "UNITID UNITID VISIBLE;UNITTYPE UNITTYPE HIDDEN;COMPKEY COMPKEY HIDDEN;COMPTYPE COMPTYPE HIDDEN;GLOBALID GLOBALID HIDDEN;OWNRSHIP OWNRSHIP HIDDEN;SERVSTAT SERVSTAT HIDDEN;DIAMETER DIAMETER HIDDEN;DEPTH DEPTH HIDDEN;VARIETY VARIETY HIDDEN;JOBNO JOBNO HIDDEN;X_COORD X_COORD VISIBLE;Y_COORD Y_COORD VISIBLE;DATA_SRC DATA_SRC HIDDEN;INSTALL_DATE INSTALL_DATE HIDDEN;EDIT_DATE EDIT_DATE HIDDEN;SYSTEM SYSTEM HIDDEN;LAYER_GROUP LAYER_GROUP HIDDEN;SYMBOL_GROUP SYMBOL_GROUP HIDDEN;DETAIL_SYMBOL DETAIL_SYMBOL HIDDEN;ROTATEANGLE ROTATEANGLE HIDDEN;DepthText DepthText HIDDEN;Elevation Elevation HIDDEN;LongFeet LongFeet VISIBLE;LatFeet LatFeet VISIBLE;LongDecimalDegrees LongDecimalDegrees VISIBLE;LatDecimalDegrees LatDecimalDegrees VISIBLE;DepthToGW2008 DepthToGW2008 HIDDEN;GWVariation2008 GWVariation2008 HIDDEN;SepDistance2008 SepDistance2008 HIDDEN;DepthToGWCSM DepthToGWCSM HIDDEN;SepDistanceCSM SepDistanceCSM HIDDEN;NearDWWell NearDWWell HIDDEN;NearIrrWell NearIrrWell HIDDEN;NearWellTaxlot NearWellTaxlot HIDDEN;NearPotentialWell NearPotentialWell HIDDEN;NearWellMin NearWellMin HIDDEN;NearWetland NearWetland HIDDEN;NearSurfaceWater NearSurfaceWater HIDDEN;NearECSI NearECSI HIDDEN;InTOT InTOT HIDDEN;GenZone GenZone HIDDEN;StreetType StreetType HIDDEN;NearWellTOTScore NearWellTOTScore HIDDEN;SepDistScore SepDistScore HIDDEN;ZoningScore ZoningScore HIDDEN;TrafficCountScore TrafficCountScore HIDDEN;PretreatmentScore PretreatmentScore HIDDEN;DistanceToSurfaceWaterScore DistanceToSurfaceWaterScore HIDDEN;StormwaterQualityScore StormwaterQualityScore HIDDEN;MobilityScore MobilityScore HIDDEN;SoilPermeabilityScore SoilPermeabilityScore HIDDEN;PriorityScore PriorityScore HIDDEN;ComplianceCategory ComplianceCategory HIDDEN")

# Process: Copy Features...
gp.CopyFeatures_management(uic_Layer1, LatLong, "", "0", "0", "0")

