# ---------------------------------------------------------------------------
# 03. CalcDepthtoGW.py
# Created on: Tue Apr 16 2013 05:26:19 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Check out any necessary licenses
gp.CheckOutExtension("spatial")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
UIC_Registration_Spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_UTM1083"
d5_masked_UTM1083_2008__1_ = "\\\\Cassio\\gis2\\PROJECTS\\7750\\UIC_DB\\ARCHIVE\\UIC_DB_RASTERS_91.gdb\\d5_masked_UTM1083_2008"
Delete_succeeded__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
UIC_Registration_DTGW2008_temp__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008_temp"
UIC_Registration_DTGW2008_temp__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008_temp"
UIC_Registration_DTGW2008_temp__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008_temp"
UIC_Registration_DTGW2008_temp__4_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008_temp"
UIC_Registration_DTGW2008__5_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
UIC_Registration_DTGW2008__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
UIC_Registration_DTGW2008__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
pdx_seasonal_flux_UTM1083__1_ = "\\\\Cassio\\gis2\\PROJECTS\\7750\\UIC_DB\\ARCHIVE\\UIC_DB_RASTERS_91.gdb\\pdx_seasonal_flux_UTM1083"
UIC_Registration_DTGW2008__4_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
UIC_Registration_DTGW2008__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008"
Delete_succeeded__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_DTGW2008_temp"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_DTGW2008__1_, "FeatureClass")

# Process: Extract Values to Points...
gp.ExtractValuesToPoints_sa(UIC_Registration_Spatial__1_, d5_masked_UTM1083_2008__1_, UIC_Registration_DTGW2008_temp__1_, "INTERPOLATE", "VALUE_ONLY")

# Process: Add Field (1)...
gp.AddField_management(UIC_Registration_DTGW2008_temp__1_, "gwDepth", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (1)...
gp.CalculateField_management(UIC_Registration_DTGW2008_temp__2_, "gwDepth", "[RASTERVALU]", "VB", "")

# Process: Delete Field (1)...
gp.DeleteField_management(UIC_Registration_DTGW2008_temp__3_, "RASTERVALU")

# Process: Extract Values to Points (2)...
gp.ExtractValuesToPoints_sa(UIC_Registration_DTGW2008_temp__4_, pdx_seasonal_flux_UTM1083__1_, UIC_Registration_DTGW2008__2_, "NONE", "VALUE_ONLY")

# Process: Add Field (2)...
gp.AddField_management(UIC_Registration_DTGW2008__2_, "gwVar", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)...
gp.CalculateField_management(UIC_Registration_DTGW2008__3_, "gwVar", "[RASTERVALU]", "VB", "")

# Process: Delete Field (2)...
gp.DeleteField_management(UIC_Registration_DTGW2008__4_, "RASTERVALU")

# Process: Delete (2)...
gp.Delete_management(UIC_Registration_DTGW2008_temp__4_, "FeatureClass")

