# ---------------------------------------------------------------------------
# 06. CalcProximityptoWells.py
# Created on: Tue Apr 16 2013 05:29:11 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
CONFIRMED_WELLS_Drinking_FeatureLayer__1_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_Irrigation_FeatureLayer__1_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"
UIC_Registration_near_Wells__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__9_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__5_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__11_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__8_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
CONFIRMED_WELLS__1_ = "Database Connections\\egh_public.sde\\EGH_PUBLIC.ARCMAP_ADMIN.uic_confirmedwells_bes_pdx"
CONFIRMED_WELLS__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\CONFIRMED_WELLS"
UIC_Registration_near_Wells__4_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial"
UIC_Registration_near_Wells__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
Delete_succeeded__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
CONFIRMED_WELLS_Drinking_FeatureLayer__5_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_Drinking_FeatureLayer__6_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_drinking_features__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\CONFIRMED_WELLS_drinking_features"
CONFIRMED_WELLS_Select__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\CONFIRMED_WELLS_Select"
UIC_Registration_near_Wells__6_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__7_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
CONFIRMED_WELLS_Irrigation_FeatureLayer__5_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"
CONFIRMED_WELLS_Irrigation_FeatureLayer__6_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"
CONFIRMED_WELLS_irrigation_features__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\CONFIRMED_WELLS_irrigation_features"
UIC_Registration_near_Wells__12_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
UIC_Registration_near_Wells__13_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Wells"
CONFIRMED_WELLS_Feature_Layer__1_ = "CONFIRMED_WELLS_Feature_Layer"
CONFIRMED_WELLS__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\CONFIRMED_WELLS"
CONFIRMED_WELLS_Drinking_FeatureLayer__3_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_Drinking_FeatureLayer__2_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_Drinking_FeatureLayer__4_ = "CONFIRMED_WELLS_Drinking_FeatureLayer"
CONFIRMED_WELLS_Irrigation_FeatureLayer__2_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"
CONFIRMED_WELLS_Irrigation_FeatureLayer__3_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"
CONFIRMED_WELLS_Irrigation_FeatureLayer__4_ = "CONFIRMED_WELLS_Irrigation_FeatureLayer"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_near_Wells__1_, "FeatureClass")

# Process: Copy Features (1)...
gp.CopyFeatures_management(UIC_Registration_spatial__1_, UIC_Registration_near_Wells__4_, "", "0", "0", "0")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(CONFIRMED_WELLS__1_, CONFIRMED_WELLS_Feature_Layer__1_, "", "", "ID ID VISIBLE NONE;LOG_NO LOG_NO VISIBLE NONE;SECONDARY_LOG_NO SECONDARY_LOG_NO VISIBLE NONE;REGISTRANT REGISTRANT VISIBLE NONE;CURRENT_OWNER_OCCUPANT CURRENT_OWNER_OCCUPANT VISIBLE NONE;TRS TRS VISIBLE NONE;ADDRESS ADDRESS VISIBLE NONE;ADDRESS0 ADDRESS0 VISIBLE NONE;PHONE PHONE VISIBLE NONE;DEPTH DEPTH VISIBLE NONE;YIELD YIELD VISIBLE NONE;DATE_ DATE_ VISIBLE NONE;USE_DRINKING USE_DRINKING VISIBLE NONE;USE_IRRIGATION USE_IRRIGATION VISIBLE NONE;USE_COMIND USE_COMIND VISIBLE NONE;USE_OTHER USE_OTHER VISIBLE NONE;METER_NO METER_NO VISIBLE NONE;ACTIVE ACTIVE VISIBLE NONE;CHECKED_BY CHECKED_BY VISIBLE NONE;COMMENTS COMMENTS VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;SOURCE_DESCRIP SOURCE_DESCRIP VISIBLE NONE;SAVED_COMMENTS SAVED_COMMENTS VISIBLE NONE;DOCUMENTED_CHANGES DOCUMENTED_CHANGES VISIBLE NONE;POINT_X POINT_X VISIBLE NONE;POINT_Y POINT_Y VISIBLE NONE;altID altID VISIBLE NONE;nearBESUIC nearBESUIC VISIBLE NONE;nearBGSUIC nearBGSUIC VISIBLE NONE;nearFireUIC nearFireUIC VISIBLE NONE;nearParksUIC nearParksUIC VISIBLE NONE;nearWaterUIC nearWaterUIC VISIBLE NONE;inTOT inTOT VISIBLE NONE")

# Process: Copy Features (3)...
gp.CopyFeatures_management(CONFIRMED_WELLS_Feature_Layer__1_, CONFIRMED_WELLS__2_, "", "0", "0", "0")

# Process: Select (1)...
gp.Select_analysis(CONFIRMED_WELLS__2_, CONFIRMED_WELLS_Select__1_, "")

# Process: Make Feature Layer (1)...
gp.MakeFeatureLayer_management(CONFIRMED_WELLS_Select__1_, CONFIRMED_WELLS_Drinking_FeatureLayer__1_, "ACTIVE = 'Yes' and [Use_Drinking] = 'Yes'", "", "")

# Process: Select Layer By Attribute (1)...
gp.SelectLayerByAttribute_management(CONFIRMED_WELLS_Drinking_FeatureLayer__1_, "NEW_SELECTION", "[altID] = 0")

# Process: Calculate Field (1)...
gp.CalculateField_management(CONFIRMED_WELLS_Drinking_FeatureLayer__2_, "altID", "[ID]", "VB", "")

# Process: Select Layer By Attribute (2)...
gp.SelectLayerByAttribute_management(CONFIRMED_WELLS_Drinking_FeatureLayer__3_, "CLEAR_SELECTION", "")

# Process: Add Field (1)...
gp.AddField_management(CONFIRMED_WELLS_Drinking_FeatureLayer__4_, "drinkingWellID", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)...
gp.CalculateField_management(CONFIRMED_WELLS_Drinking_FeatureLayer__5_, "drinkingWellID", "[altID]", "VB", "")

# Process: Copy Features (2)...
gp.CopyFeatures_management(CONFIRMED_WELLS_Drinking_FeatureLayer__6_, CONFIRMED_WELLS_drinking_features__1_, "", "0", "0", "0")

# Process: Near (1)...
gp.Near_analysis(UIC_Registration_near_Wells__4_, "CONFIRMED_WELLS_Drinking_FeatureLayer", "", "NO_LOCATION", "NO_ANGLE")

# Process: Calculate Field (3)...
gp.CalculateField_management(UIC_Registration_near_Wells__3_, "nearDWWell", "[NEAR_DIST]", "VB", "")

# Process: Add Field (3)...
gp.AddField_management(UIC_Registration_near_Wells__5_, "nearDrinkingWellObjID", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)...
gp.CalculateField_management(UIC_Registration_near_Wells__6_, "nearDrinkingWellObjID", "[NEAR_FID]", "VB", "")

# Process: Delete Field (2)...
gp.DeleteField_management(UIC_Registration_near_Wells__7_, "NEAR_FID;NEAR_DIST")

# Process: Make Feature Layer (2)...
gp.MakeFeatureLayer_management(CONFIRMED_WELLS__3_, CONFIRMED_WELLS_Irrigation_FeatureLayer__1_, "[Use_Irrigation] = 'Yes' AND ACTIVE = 'Yes' ", "", "ID ID VISIBLE NONE;LOG_NO LOG_NO VISIBLE NONE;SECONDARY_LOG_NO SECONDARY_LOG_NO VISIBLE NONE;REGISTRANT REGISTRANT VISIBLE NONE;CURRENT_OWNER_OCCUPANT CURRENT_OWNER_OCCUPANT VISIBLE NONE;TRS TRS VISIBLE NONE;ADDRESS ADDRESS VISIBLE NONE;ADDRESS0 ADDRESS0 VISIBLE NONE;PHONE PHONE VISIBLE NONE;DEPTH DEPTH VISIBLE NONE;YIELD YIELD VISIBLE NONE;DATE_ DATE_ VISIBLE NONE;USE_DRINKING USE_DRINKING VISIBLE NONE;USE_IRRIGATION USE_IRRIGATION VISIBLE NONE;USE_COMIND USE_COMIND VISIBLE NONE;USE_OTHER USE_OTHER VISIBLE NONE;METER_NO METER_NO VISIBLE NONE;ACTIVE ACTIVE VISIBLE NONE;CHECKED_BY CHECKED_BY VISIBLE NONE;COMMENTS COMMENTS VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;SOURCE_DESCRIP SOURCE_DESCRIP VISIBLE NONE;SAVED_COMMENTS SAVED_COMMENTS VISIBLE NONE;DOCUMENTED_CHANGES DOCUMENTED_CHANGES VISIBLE NONE;POINT_X POINT_X VISIBLE NONE;POINT_Y POINT_Y VISIBLE NONE;altID altID VISIBLE NONE;nearBESUIC nearBESUIC VISIBLE NONE;nearBGSUIC nearBGSUIC VISIBLE NONE;nearFireUIC nearFireUIC VISIBLE NONE;nearParksUIC nearParksUIC VISIBLE NONE;nearWaterUIC nearWaterUIC VISIBLE NONE;inTOT inTOT VISIBLE NONE;irrigationWellID irrigationWellID VISIBLE NONE")

# Process: Select Layer By Attribute (3)...
gp.SelectLayerByAttribute_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__1_, "NEW_SELECTION", "[altID] = 0")

# Process: Calculate Field (5)...
gp.CalculateField_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__2_, "altID", "[ID]", "VB", "")

# Process: Select Layer By Attribute (4)...
gp.SelectLayerByAttribute_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__3_, "CLEAR_SELECTION", "")

# Process: Add Field...
gp.AddField_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__4_, "irrigationWellID", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (6)...
gp.CalculateField_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__5_, "irrigationWellID", "[altID]", "VB", "")

# Process: Copy Features...
gp.CopyFeatures_management(CONFIRMED_WELLS_Irrigation_FeatureLayer__6_, CONFIRMED_WELLS_irrigation_features__1_, "", "0", "0", "0")

# Process: Near (10)...
gp.Near_analysis(UIC_Registration_near_Wells__8_, "CONFIRMED_WELLS_Irrigation_FeatureLayer", "", "NO_LOCATION", "NO_ANGLE")

# Process: Calculate Field (7)...
gp.CalculateField_management(UIC_Registration_near_Wells__9_, "nearIrrWell", "[NEAR_DIST]", "VB", "")

# Process: Add Field (5)...
gp.AddField_management(UIC_Registration_near_Wells__11_, "nearIrrigationWellObjID", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (8)...
gp.CalculateField_management(UIC_Registration_near_Wells__12_, "nearIrrigationWellObjID", "[NEAR_FID]", "VB", "")

# Process: Delete Field (11)...
gp.DeleteField_management(UIC_Registration_near_Wells__13_, "NEAR_FID;NEAR_DIST")

