# ---------------------------------------------------------------------------
# 07. CalcZoning.py
# Created on: Tue Apr 16 2013 05:29:41 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
PDX_Zoning__1_ = "\\\\Cassio\\gis2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\UIC_PDX_Zoning"
UIC_Registration_Zoning = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Zoning"
UIC_Registration_Spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial"
UIC_Registration_Zoning__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Zoning"
Delete_succeeded__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Zoning"
PDX_Zoning__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\PDX_Zoning"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_Zoning__1_, "FeatureClass")

# Process: Copy (1)...
gp.Copy_management(PDX_Zoning__1_, PDX_Zoning__2_, "FeatureClass")

# Process: Intersect (1)...
gp.Intersect_analysis("\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\PDX_Zoning #;\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial #", UIC_Registration_Zoning, "NO_FID", "", "INPUT")

