# ---------------------------------------------------------------------------
# 09. CalcDisttoSurfaceWater.py
# Created on: Tue Apr 16 2013 05:31:26 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
UIC_Registration_near_Surfacewater__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Surfacewater"
Waterbodies_pdx_pt__1_ = "\\\\Cassio\\gis2\\PROJECTS\\7750\\UIC_DB\\UIC_DATABASE_91.mdb\\Waterbodies_pdx_pt"
UIC_Registration_Spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial"
UIC_Registration_near_Surfacewater__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Surfacewater"
UIC_Registration_near_Surfacewater__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Surfacewater"
Delete_succeeded__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_near_Surfacewater"
Waterbodies_pdx_pt__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\Waterbodies_pdx_pt"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_near_Surfacewater__1_, "FeatureClass")

# Process: Copy Features (1)...
gp.CopyFeatures_management(UIC_Registration_Spatial__1_, UIC_Registration_near_Surfacewater__2_, "", "0", "0", "0")

# Process: Copy...
gp.Copy_management(Waterbodies_pdx_pt__1_, Waterbodies_pdx_pt__2_, "FeatureClass")

# Process: Near analysis (1)...
gp.Near_analysis(UIC_Registration_near_Surfacewater__2_, "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\Waterbodies_pdx_pt", "", "NO_LOCATION", "NO_ANGLE")

