# ---------------------------------------------------------------------------
# 11. CalcStreetType.py
# Created on: Tue Apr 16 2013 05:32:48 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
UIC_Registration_Spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial"
UIC_Registration_Spatial_50ft_bfr__2_ = "c:\\temp\\UIC_Registration_Spatial_50ft_bfr.shp"
PDOT_TSP__1_ = "Database Connections\\egh_public.sde\\EGH_Public.ARCMAP_ADMIN.tsp_classifications_pdx"
UIC_TSP_clip2_50ft_bfr__2_ = "c:\\temp\\UIC_TSP_clip2_50ft_bfr.shp"
UIC_Registration_Spatial_50ftbfr_Ident_TSP__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial_50ftbfr_Ident_TSP"
UIC_Registration_Spatial_50ftbfr_Ident_TSP__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial_50ftbfr_Ident_TSP"
Delete_succeeded__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial_50ftbfr_Ident_TSP"

# Process: Buffer (1)...
gp.Buffer_analysis(UIC_Registration_Spatial__1_, UIC_Registration_Spatial_50ft_bfr__2_, "50 Feet", "FULL", "ROUND", "NONE", "")

# Process: Clip (1)...
gp.Clip_analysis(PDOT_TSP__1_, UIC_Registration_Spatial_50ft_bfr__2_, UIC_TSP_clip2_50ft_bfr__2_, "")

# Process: Delete (3)...
gp.Delete_management(UIC_Registration_Spatial_50ftbfr_Ident_TSP__1_, "FeatureClass")

# Process: Identity (1)...
gp.Identity_analysis(UIC_TSP_clip2_50ft_bfr__2_, UIC_Registration_Spatial_50ft_bfr__2_, UIC_Registration_Spatial_50ftbfr_Ident_TSP__2_, "ALL", "", "NO_RELATIONSHIPS")

