# ---------------------------------------------------------------------------
# 13. CopyLocatorCoverages.py
# Created on: Tue Apr 16 2013 05:34:27 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
UIC_Registration_Spatial__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_Spatial"
UIC_Registration_Spatial__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial"
Delete_succeeded__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial"
UIC_Registration_Spatial__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_Spatial"
UIC_Registration_temp_SSCs__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Locator.mdb\\UIC_Registration_tempSSCs"
UIC_Registration_temp_SSCs__1_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_tempSSCs"
Delete_succeeded__2_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_tempSSCs"
UIC_Registration_tempSSCs__3_ = "\\\\cassio\\gis2\\PROJECTS\\7750\\Registrations\\UIC_Registration.mdb\\UIC_Registration_tempSSCs"

# Process: Delete (1)...
gp.Delete_management(UIC_Registration_Spatial__1_, "FeatureClass")

# Process: Delete (2)...
gp.Delete_management(UIC_Registration_temp_SSCs__1_, "FeatureClass")

# Process: Copy (2)...
gp.Copy_management(UIC_Registration_temp_SSCs__2_, UIC_Registration_tempSSCs__3_, "FeatureClass")

# Process: Copy (1)...
gp.Copy_management(UIC_Registration_Spatial__2_, UIC_Registration_Spatial__3_, "FeatureClass")

